### ISSUE TITLE
Change dependency on R to >3.5.0

### ISSUE THREAD

**Issue by matthewlewis896** [iiasa/rN2000#2]
Warnings on install flag change in dependency due to use of `load()`.

`WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.`

Minor issue with no implications for install, but will need to be fixed for CRAN.

**Comment by Martin-Jung** [comment]
Changed dependency description

**Comment by matthewlewis896** [comment]
Awesome thanks!
